// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXie4QKoFngaX3jUxzk7nv9IBSzZN0OC4',
    appId: '1:55308562959:web:3b9ea0b55d999eed28e97a',
    messagingSenderId: '55308562959',
    projectId: 'timebuddy-e91c9',
    authDomain: 'timebuddy-e91c9.firebaseapp.com',
    storageBucket: 'timebuddy-e91c9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0kPHyWJlZzS_aOLYuvoBUiGOR5zatnyM',
    appId: '1:55308562959:android:664d788f3d98f41028e97a',
    messagingSenderId: '55308562959',
    projectId: 'timebuddy-e91c9',
    storageBucket: 'timebuddy-e91c9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjn9KrejaOjr6ZgQX1YqpOfruHHcHkogo',
    appId: '1:55308562959:ios:334c60ab5fcfc39628e97a',
    messagingSenderId: '55308562959',
    projectId: 'timebuddy-e91c9',
    storageBucket: 'timebuddy-e91c9.firebasestorage.app',
    iosBundleId: 'com.example.timebuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjn9KrejaOjr6ZgQX1YqpOfruHHcHkogo',
    appId: '1:55308562959:ios:334c60ab5fcfc39628e97a',
    messagingSenderId: '55308562959',
    projectId: 'timebuddy-e91c9',
    storageBucket: 'timebuddy-e91c9.firebasestorage.app',
    iosBundleId: 'com.example.timebuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXie4QKoFngaX3jUxzk7nv9IBSzZN0OC4',
    appId: '1:55308562959:web:927c8a2b376d8e2c28e97a',
    messagingSenderId: '55308562959',
    projectId: 'timebuddy-e91c9',
    authDomain: 'timebuddy-e91c9.firebaseapp.com',
    storageBucket: 'timebuddy-e91c9.firebasestorage.app',
  );
}
